# Generated by Django 4.2.2 on 2023-07-03 18:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('employee', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userregistration',
            name='last_login',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
